// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MediaReader is an autogenerated mock type for the MediaReader type
type MediaReader struct {
	mock.Mock
}

// Read provides a mock function with given fields: filePath
func (_m *MediaReader) Read(filePath string) ([][]byte, error) {
	ret := _m.Called(filePath)

	if len(ret) == 0 {
		panic("no return value specified for Read")
	}

	var r0 [][]byte
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([][]byte, error)); ok {
		return rf(filePath)
	}
	if rf, ok := ret.Get(0).(func(string) [][]byte); ok {
		r0 = rf(filePath)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([][]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(filePath)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMediaReader creates a new instance of MediaReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMediaReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MediaReader {
	mock := &MediaReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
