// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MediaReader is an autogenerated mock type for the MediaReader type
type MediaReader struct {
	mock.Mock
}

type MediaReader_Expecter struct {
	mock *mock.Mock
}

func (_m *MediaReader) EXPECT() *MediaReader_Expecter {
	return &MediaReader_Expecter{mock: &_m.Mock}
}

// Read provides a mock function with given fields: filePath
func (_m *MediaReader) Read(filePath string) ([][]byte, error) {
	ret := _m.Called(filePath)

	if len(ret) == 0 {
		panic("no return value specified for Read")
	}

	var r0 [][]byte
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([][]byte, error)); ok {
		return rf(filePath)
	}
	if rf, ok := ret.Get(0).(func(string) [][]byte); ok {
		r0 = rf(filePath)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([][]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(filePath)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MediaReader_Read_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Read'
type MediaReader_Read_Call struct {
	*mock.Call
}

// Read is a helper method to define mock.On call
//   - filePath string
func (_e *MediaReader_Expecter) Read(filePath interface{}) *MediaReader_Read_Call {
	return &MediaReader_Read_Call{Call: _e.mock.On("Read", filePath)}
}

func (_c *MediaReader_Read_Call) Run(run func(filePath string)) *MediaReader_Read_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MediaReader_Read_Call) Return(_a0 [][]byte, _a1 error) *MediaReader_Read_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MediaReader_Read_Call) RunAndReturn(run func(string) ([][]byte, error)) *MediaReader_Read_Call {
	_c.Call.Return(run)
	return _c
}

// NewMediaReader creates a new instance of MediaReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMediaReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MediaReader {
	mock := &MediaReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
