// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ModelRunner is an autogenerated mock type for the ModelRunner type
type ModelRunner struct {
	mock.Mock
}

// Infer provides a mock function with given fields: data
func (_m *ModelRunner) Infer(data [][]byte) ([]float32, error) {
	ret := _m.Called(data)

	if len(ret) == 0 {
		panic("no return value specified for Infer")
	}

	var r0 []float32
	var r1 error
	if rf, ok := ret.Get(0).(func([][]byte) ([]float32, error)); ok {
		return rf(data)
	}
	if rf, ok := ret.Get(0).(func([][]byte) []float32); ok {
		r0 = rf(data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]float32)
		}
	}

	if rf, ok := ret.Get(1).(func([][]byte) error); ok {
		r1 = rf(data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewModelRunner creates a new instance of ModelRunner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewModelRunner(t interface {
	mock.TestingT
	Cleanup(func())
}) *ModelRunner {
	mock := &ModelRunner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
