// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ModelRunner is an autogenerated mock type for the ModelRunner type
type ModelRunner struct {
	mock.Mock
}

type ModelRunner_Expecter struct {
	mock *mock.Mock
}

func (_m *ModelRunner) EXPECT() *ModelRunner_Expecter {
	return &ModelRunner_Expecter{mock: &_m.Mock}
}

// Infer provides a mock function with given fields: data
func (_m *ModelRunner) Infer(data [][]byte) ([]float32, error) {
	ret := _m.Called(data)

	if len(ret) == 0 {
		panic("no return value specified for Infer")
	}

	var r0 []float32
	var r1 error
	if rf, ok := ret.Get(0).(func([][]byte) ([]float32, error)); ok {
		return rf(data)
	}
	if rf, ok := ret.Get(0).(func([][]byte) []float32); ok {
		r0 = rf(data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]float32)
		}
	}

	if rf, ok := ret.Get(1).(func([][]byte) error); ok {
		r1 = rf(data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ModelRunner_Infer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Infer'
type ModelRunner_Infer_Call struct {
	*mock.Call
}

// Infer is a helper method to define mock.On call
//   - data [][]byte
func (_e *ModelRunner_Expecter) Infer(data interface{}) *ModelRunner_Infer_Call {
	return &ModelRunner_Infer_Call{Call: _e.mock.On("Infer", data)}
}

func (_c *ModelRunner_Infer_Call) Run(run func(data [][]byte)) *ModelRunner_Infer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([][]byte))
	})
	return _c
}

func (_c *ModelRunner_Infer_Call) Return(_a0 []float32, _a1 error) *ModelRunner_Infer_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ModelRunner_Infer_Call) RunAndReturn(run func([][]byte) ([]float32, error)) *ModelRunner_Infer_Call {
	_c.Call.Return(run)
	return _c
}

// NewModelRunner creates a new instance of ModelRunner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewModelRunner(t interface {
	mock.TestingT
	Cleanup(func())
}) *ModelRunner {
	mock := &ModelRunner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
